### ISSUE TITLE
Uncaught Invariant Violation: Internal Error: may not update existing query string in store

### ISSUE THREAD

**Issue by FezVrasta** [molindo/react-apollo-network-status#15] opened 2019-06-06 12:32 UTC
Hi, I'm trying to upgrade from 1.0.0 to 2.0.0 but as soon I wrap my app into `<ApolloNetworkStatusProvider>` I get this error on some of the queries (some work, some don't):

```
Uncaught Invariant Violation: Internal Error: may not update existing query string in store
```

The code is basically:

```jsx
import { ApolloProvider } from 'react-apollo';
import { ApolloProvider as ApolloHooksProvider } from '@apollo/react-hooks';
import { ApolloNetworkStatusProvider } from 'react-apollo-network-status';

[...]

<ApolloProvider client={client}>
  <ApolloHooksProvider client={client}>
    <ApolloNetworkStatusProvider>
      <App />
    </ApolloNetworkStatusProvider>
  </ApolloHooksProvider>
</ApolloProvider>
```

**Comment by amannn** [comment] 2019-06-06 15:35
Thanks for the bug report!

It looks like you're using the beta version of `@apollo/react-hooks`. Maybe the issue is related to using both `react-apollo` and the hooks version together.

I will have to update this library with the release of the hooks version of Apollo, as they're using a new context provider there. Therefore the components that are using `useQuery` and `useMutation` won't affect the network status currently.

I did a quick experiment with the current beta of the hooks version, but found some issues. I think I'll wait until the package becomes stable and then see what changes are necessary and release a new version.

I recommend you to stay on the 1.0 version until then.

However it would be interesting to learn more about your use case. You're saying that some queries work while others don't. Can you tell what the difference between them is? Is there a special feature you're using, like local state? A reduced code sandbox example that triggers the error would be ideal ([template](https://codesandbox.io/s/reactapollonetworkstatus-classic-46s5t)).

**Comment by FezVrasta** [comment] 2019-06-06 16:16
Thanks for the quick reply.

Unfortunately I don't have much time to allocate to this upgrade, the 1.0 version works fine so the upgrade is not a priority.

I can't seem to find anything specific that I'm using in the queries that fail, I use `useQuery` almost everywhere (we are still migrating some old components).

**Comment by amannn** [comment] 2019-06-07 05:29
Ok, I see. Well `useQuery` not working is expected, since they switched to a new context provider.

When the Apollo hooks get a stable release I'll test again with them and see if I can make a new release that supports them.

**Comment by amannn** [comment] 2019-09-27 06:36
I'll close this in favour of https://github.com/molindo/react-apollo-network-status/issues/16.

**Closed by amannn** 2019-09-27 06:36 UTC
