### ISSUE TITLE
useApolloNetworkStatus() doesn't react on query?

### ISSUE THREAD

**Issue by github0013** [molindo/react-apollo-network-status#36] opened 2020-11-20 01:55 UTC
```tsx
function GlobalLoadingIndicator() {
  const status = useApolloNetworkStatus()
  console.log("status.numPendingQueries", status.numPendingQueries)
  if (status.numPendingQueries > 0) {
    return <p>Loading …</p>
  } else {
    return null
  }
}

const App = () => {
  const { loading, error, data } = useQuery(Query)
  console.log("loading", loading)
  console.log("data", data)

  return <></>
}
```

# expected

- status.numPendingQueries 0
- loading true
- data undefined
- status.numPendingQueries 1
- loading false
- data {GenreCollection: Array(19)}
- status.numPendingQueries 0

Order might be different, but I at least was expecting `status.numPendingQueries` would become 1, but it never happens.

# actual
![react-apollo-network-status_-_CodeSandbox](https://user-images.githubusercontent.com/809378/99747575-1f5af500-2b1e-11eb-9208-cd7e08b5b796.png)

# codesandbox
https://codesandbox.io/s/typescript-react-material-ui-5zxqh

I copied the sample code from readme, and added `App` to it.  How is my code not running properly?

**Comment by amannn** [comment] 2020-11-20 09:08
Thanks for the report!

Yes, this is a known limitation at this point. I think this is a duplicate of https://github.com/molindo/react-apollo-network-status/issues/19.

The topic is a bit tough because Apollo fetches data during render which is before the subscription is set up (`useEffect`). I've wrote about some potential solutions here: https://github.com/molindo/react-apollo-network-status/issues/19#issuecomment-576265248.

Thank you for the reproduction!

**Closed by amannn** 2020-11-20 09:08 UTC
